# Generated by Django 4.2.10 on 2024-02-20 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forumapp', '0005_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('family', 'Family'), ('pastimes', 'Pastimes'), ('career', 'Career'), ('wall_of_complaints', 'Wall of Complaints')], default='pastimes', max_length=100),
        ),
    ]
