# Generated by Django 4.2.10 on 2024-02-26 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forumapp', '0006_post_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='body',
            new_name='content',
        ),
    ]
