# Generated by Django 4.2.10 on 2024-02-27 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forumapp', '0007_rename_body_comment_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermsAndConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
        ),
    ]
