# Generated by Django 4.2.10 on 2024-02-29 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forumapp', '0008_termsandconditions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=1),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
